name: Yoo Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: yoo_runner1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm i

      - name: Build Project
        run: npm run build

      # # Upload the build artifacts (e.g., dist folder or build package)
      # - name: Upload Build Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build-package
      #     path: ./dist/  # Assuming the build files are in the 'dist' directory. Modify this path if needed.

      # If you need to publish the package to npm or GitHub Packages, uncomment this section
      # - name: Publish to npm registry
      #   run: npm publish --access public  # If you want to publish your package
